# Generated by Django 3.2.4 on 2021-06-03 11:39

import cpf_field.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_cliente', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('email_cliente', models.CharField(max_length=255)),
            ],
        ),
    ]
